# Generated by Django 2.0.2 on 2018-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=80)),
                ('file_size', models.IntegerField(blank=True)),
                ('file_date', models.DateField()),
                ('is_subtitle', models.BooleanField()),
                ('has_subtitle', models.BooleanField()),
            ],
        ),
    ]
