# Generated by Django 2.0.2 on 2018-03-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='file_list',
            name='file_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='file_list',
            name='m_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='viewer.movie_name'),
            preserve_default=False,
        ),
    ]
