# Generated by Django 2.0.2 on 2018-03-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20180324_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_list',
            name='has_subtitle',
        ),
        migrations.AddField(
            model_name='movie_name',
            name='has_subtitle',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
