# Generated by Django 2.0.2 on 2018-03-27 21:02

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_name',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['moviename']),
        ),
    ]
