# Generated by Django 2.0.2 on 2018-03-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_movie_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_name',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20, unique=True), unique=True),
        ),
    ]
