# Generated by Django 2.0.2 on 2018-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20180327_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_name',
            name='slug',
        ),
        migrations.AlterField(
            model_name='movie_name',
            name='moviename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
