# Generated by Django 2.0.2 on 2018-03-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_auto_20180330_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_list',
            name='is_subtitle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie_name',
            name='has_subtitle',
            field=models.BooleanField(default=False),
        ),
    ]
