# Generated by Django 2.0.2 on 2018-03-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_auto_20180330_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_list',
            name='file_size',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
